config/routes.rb
Rails.application.routes.draw do

  resources :genres
  resources :users
  get "signup" => "users#new"
  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  resources :movies do
    resources :reviews
    resources :favorites, only: %i[create destroy]
  end

  resource :session, only: %i[new create destroy]
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/characterization.rb
class Characterization < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations

end

app/models/movie.rb
class Movie < ApplicationRecord

  before_save :set_slug

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :released_on, :duration, presence: true
  validates :title, presence: true, uniqueness: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :rating, inclusion: { in: RATINGS }

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations

  scope :released, -> { where("released_on < ?", Time.now).order("released_on desc") }
  scope :upcoming, -> { where("released_on > ?", Time.now).order("released_on asc") }

  scope :recent, ->(max=5) { released.limit(max) }

  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end

  def set_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
  

end

app/models/review.rb
class Review < ApplicationRecord
  STARS = [1, 2, 3, 4, 5]

  belongs_to :movie
  belongs_to :user
  validates :comment, length: { minimum: 4 }


  validates :stars, inclusion: {
    in: STARS,
    message: "must be between 1 and 5"
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_signin
  before_action :set_movie
  
  def create
    @movie.favorites.create!(user: current_user)
    redirect_to @movie, notice: 'Movie added to favorites'
  end

  def destroy
    favorite = current_user.favorites.find(params[:id])
    favorite.destroy
    redirect_to @movie, notice: 'Movie removed from favorites'
  end

  private

  def set_movie
    @movie = Movie.find_by!(slug: params[:movie_id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_signin, except: %i[index show]
  before_action :require_admin, except: %i[index show]
  before_action :set_movie, only: %i[show edit update destroy]

  def index
    case params[:filter]
    when "upcoming"
      @movies = Movie.upcoming
    when "recent"
      @movies = Movie.recent
    else
      @movies = Movie.released
    end
  end

  def show
    if current_user
      @favorite = current_user.favorites.find_by(movie_id: @movie.id)
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie was created successfully'
    else
      flash.now[:alert] = 'Movie could not be created'
      render :new
    end
  end

  def edit; end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie was updated'
    else
      flash.now[:alert] = 'Movie could not be updated'
      render :edit
    end
  end

  def destroy
    if @movie.destroy
      flash[:notice] = 'Movie was deleted'
    else
      flash[:notice] = 'We could not delete this movie'
    end
    redirect_to movies_path
  end

  private

  def set_movie
    @movie = Movie.includes(:fans).includes(:genres).find_by!(slug: params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :rating, :released_on, :description, :total_gross, :director, :duration, :image_file_name, genre_ids: [])
  end

  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_signin
  before_action :set_movie

  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)

    if @review.save
      redirect_to @movie, notice: 'Review Submitted'
    else
      flash.now[:alert] = 'Review could not be created'
      render :new
    end
  end

  private

  def set_movie
    @movie = Movie.find_by!(slug: params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:comment, :stars).merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user, notice: "Welcome back, #{user.name}"
    else
      flash.now[:alert] = 'Invalid email/password combination!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You have successfully signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show destroy edit update]
  before_action :require_signin, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      flash.now[:alert] = 'You couldnt sign up'
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account was updated'
    else
      flash.now[:alert] = 'We couldnt update your account'
      render :edit
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_url, notice: "You're now signed out!"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.includes(:reviews).includes(:favorite_movies).find(params[:id])
  end
  def require_correct_user
    unless current_user?(@user)
      redirect_to root_path, alert: 'You are not authorized to do that!'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def fave_or_unfave_button(movie, favorite)
    if favorite
      button_to "Unfave", movie_favorite_path(movie, favorite), method: :delete
    else
      button_to "Fave", movie_favorites_path(movie)
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def total_gross(movie)
    if movie.flop?
      'Flop'
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end

  def year_of(movie)
    movie.released_on.year
  end

  def average_stars(movie)
    if movie.average_stars.zero?
      content_tag(:strong, "No reviews")
    else
      pluralize(number_with_precision(movie.average_stars, precision: 1) , "star")
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag('logo.png'), root_path %>
    <ul class="left">
      <li>
        <%= link_to 'Released', movies_path %>
      </li>
      <li>
        <%= link_to 'Upcoming', filtered_movies_path(:upcoming) %>
      </li>
      <li>
        <%= link_to 'Recent', filtered_movies_path(:recent) %>
      </li>

    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, user_path(current_user) %>  
        </li>
        <li>
          <%= link_to 'Account Settings', edit_user_path(current_user) %>
        </li>

        <li>
          <%= link_to 'Sign out', session_path, method: :delete, class: 'button' %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Sign Up', signup_path , class:'button'%>
        </li>
        <li>
          <%= link_to 'Sign In', new_session_path , class:'button'%>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlixRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <%= render 'layouts/header' %>
    <div class="content">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>